version: '3.9'
services:
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=event_scheduler
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6000:6379"
    restart: always
    command: redis-server --appendonly yes
  
  asynqmon:
    image: hibiken/asynqmon
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=12345
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=event_scheduler
      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

volumes:
  postgres_data: