ALTER TABLE events
ADD COLUMN run_at TIMESTAMP DEFAULT NULL;

ALTER TABLE events
ADD COLUMN after_x_mins INTEGER DEFAULT 0;

ALTER TABLE events
ADD COLUMN is_recurring BOOLEAN DEFAULT false;

ALTER TABLE events
ADD COLUMN interval INTEGER DEFAULT 0;
