// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: events.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  name,
  type,
  api_end_point,
  api_method,
  api_request_body,
  created_by 
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, type, api_end_point, api_method, api_request_body, created_by, created_at, executed_at
`

type CreateEventParams struct {
	Name           string
	Type           EventTypes
	ApiEndPoint    string
	ApiMethod      sql.NullString
	ApiRequestBody pqtype.NullRawMessage
	CreatedBy      string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.Type,
		arg.ApiEndPoint,
		arg.ApiMethod,
		arg.ApiRequestBody,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ApiEndPoint,
		&i.ApiMethod,
		&i.ApiRequestBody,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, type, api_end_point, api_method, api_request_body, created_by, created_at, executed_at FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ApiEndPoint,
		&i.ApiMethod,
		&i.ApiRequestBody,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, type, api_end_point, api_method, api_request_body, created_by, created_at, executed_at FROM events
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ApiEndPoint,
			&i.ApiMethod,
			&i.ApiRequestBody,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
