// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: logs.sql

package db

import (
	"context"
	"time"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (
  event_id,
  executed_on,
  status
) VALUES (
  $1, $2, $3
)
RETURNING id, event_id, executed_on, status, is_archived
`

type CreateLogParams struct {
	EventID    int64
	ExecutedOn time.Time
	Status     StatusTypes
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog, arg.EventID, arg.ExecutedOn, arg.Status)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ExecutedOn,
		&i.Status,
		&i.IsArchived,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM logs
WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLog, id)
	return err
}

const getLog = `-- name: GetLog :one
SELECT id, event_id, executed_on, status, is_archived FROM logs
WHERE id = $1
`

func (q *Queries) GetLog(ctx context.Context, id int64) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLog, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ExecutedOn,
		&i.Status,
		&i.IsArchived,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, event_id, executed_on, status, is_archived FROM logs
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ExecutedOn,
			&i.Status,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
