// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type EventTypes string

const (
	EventTypesAPI       EventTypes = "API"
	EventTypesSCHEDULED EventTypes = "SCHEDULED"
)

func (e *EventTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventTypes(s)
	case string:
		*e = EventTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for EventTypes: %T", src)
	}
	return nil
}

type NullEventTypes struct {
	EventTypes EventTypes
	Valid      bool // Valid is true if EventTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventTypes) Scan(value interface{}) error {
	if value == nil {
		ns.EventTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventTypes), nil
}

type StatusTypes string

const (
	StatusTypesSUCCESS StatusTypes = "SUCCESS"
	StatusTypesFAILED  StatusTypes = "FAILED"
)

func (e *StatusTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusTypes(s)
	case string:
		*e = StatusTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusTypes: %T", src)
	}
	return nil
}

type NullStatusTypes struct {
	StatusTypes StatusTypes
	Valid       bool // Valid is true if StatusTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusTypes) Scan(value interface{}) error {
	if value == nil {
		ns.StatusTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusTypes), nil
}

type Event struct {
	ID             int64
	Name           string
	Type           EventTypes
	ApiEndPoint    string
	ApiMethod      sql.NullString
	ApiRequestBody pqtype.NullRawMessage
	CreatedBy      string
	CreatedAt      time.Time
	ExecutedAt     sql.NullTime
}

type Log struct {
	ID         int64
	EventID    int64
	ExecutedOn time.Time
	Status     StatusTypes
	IsArchived sql.NullBool
}

type User struct {
	Username          string
	FullName          string
	Email             string
	HashedPassword    string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
