// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id int64) error
	DeleteLog(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetLog(ctx context.Context, id int64) (Log, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
	ListUserEvents(ctx context.Context, arg ListUserEventsParams) ([]Event, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
