// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/musthafa-vakkayil/event_scheduler_v2/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// DeletePattern provides a mock function with given fields: ctx, pattern
func (_m *Cache) DeletePattern(ctx context.Context, pattern string) error {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for DeletePattern")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pattern)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, archived, active, page, size
func (_m *Cache) Get(ctx context.Context, archived bool, active bool, page int, size int) ([]models.LogsResponse, error) {
	ret := _m.Called(ctx, archived, active, page, size)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.LogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, bool, int, int) ([]models.LogsResponse, error)); ok {
		return rf(ctx, archived, active, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, bool, int, int) []models.LogsResponse); ok {
		r0 = rf(ctx, archived, active, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, bool, int, int) error); ok {
		r1 = rf(ctx, archived, active, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, logs, archived, active, page, size, expiry
func (_m *Cache) Set(ctx context.Context, logs []models.LogsResponse, archived bool, active bool, page int, size int, expiry time.Duration) error {
	ret := _m.Called(ctx, logs, archived, active, page, size, expiry)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.LogsResponse, bool, bool, int, int, time.Duration) error); ok {
		r0 = rf(ctx, logs, archived, active, page, size, expiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
