// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "github.com/musthafa-vakkayil/event_scheduler_v2/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: event
func (_m *Repository) CreateEvent(event models.Event) (models.Event, error) {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Event) (models.Event, error)); ok {
		return rf(event)
	}
	if rf, ok := ret.Get(0).(func(models.Event) models.Event); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Get(0).(models.Event)
	}

	if rf, ok := ret.Get(1).(func(models.Event) error); ok {
		r1 = rf(event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSession provides a mock function with given fields: session
func (_m *Repository) CreateSession(session models.Session) (models.Session, error) {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Session) (models.Session, error)); ok {
		return rf(session)
	}
	if rf, ok := ret.Get(0).(func(models.Session) models.Session); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(models.Session) error); ok {
		r1 = rf(session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: user
func (_m *Repository) CreateUser(user models.User) (models.User, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(models.User) (models.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.User) models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: eventID
func (_m *Repository) DeleteEvent(eventID int64) error {
	ret := _m.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLog provides a mock function with given fields: logID
func (_m *Repository) DeleteLog(logID int) error {
	ret := _m.Called(logID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(logID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: username
func (_m *Repository) DeleteUser(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteEvent provides a mock function with given fields: eventID, status
func (_m *Repository) ExecuteEvent(eventID int64, status string) (int64, error) {
	ret := _m.Called(eventID, status)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteEvent")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (int64, error)); ok {
		return rf(eventID, status)
	}
	if rf, ok := ret.Get(0).(func(int64, string) int64); ok {
		r0 = rf(eventID, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(eventID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvent provides a mock function with given fields: id
func (_m *Repository) GetEvent(id int) (models.Event, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Event, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Event); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Event)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSession provides a mock function with given fields: id
func (_m *Repository) GetSession(id uuid.UUID) (models.Session, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Session, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Session); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: username
func (_m *Repository) GetUser(username string) (models.User, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEvents provides a mock function with given fields: limit, offset
func (_m *Repository) ListEvents(limit int, offset int) ([]models.Event, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Event, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Event); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLogs provides a mock function with given fields: onlyActive, onlyArchived, limit, offset
func (_m *Repository) ListLogs(onlyActive bool, onlyArchived bool, limit int, offset int) ([]models.LogsResponse, error) {
	ret := _m.Called(onlyActive, onlyArchived, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListLogs")
	}

	var r0 []models.LogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(bool, bool, int, int) ([]models.LogsResponse, error)); ok {
		return rf(onlyActive, onlyArchived, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(bool, bool, int, int) []models.LogsResponse); ok {
		r0 = rf(onlyActive, onlyArchived, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(bool, bool, int, int) error); ok {
		r1 = rf(onlyActive, onlyArchived, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkLogAsArchived provides a mock function with given fields: logID
func (_m *Repository) MarkLogAsArchived(logID int) error {
	ret := _m.Called(logID)

	if len(ret) == 0 {
		panic("no return value specified for MarkLogAsArchived")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(logID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
