// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TaskManager is an autogenerated mock type for the TaskManager type
type TaskManager struct {
	mock.Mock
}

// EnqueueArchiveTask provides a mock function with given fields: ctx, logID, delay
func (_m *TaskManager) EnqueueArchiveTask(ctx context.Context, logID int, delay time.Duration) error {
	ret := _m.Called(ctx, logID, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueArchiveTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Duration) error); ok {
		r0 = rf(ctx, logID, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueDeleteTask provides a mock function with given fields: ctx, logID, delay
func (_m *TaskManager) EnqueueDeleteTask(ctx context.Context, logID int, delay time.Duration) error {
	ret := _m.Called(ctx, logID, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Duration) error); ok {
		r0 = rf(ctx, logID, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueScheduleTaskAt provides a mock function with given fields: ctx, eventID, _a2
func (_m *TaskManager) EnqueueScheduleTaskAt(ctx context.Context, eventID int64, _a2 time.Time) error {
	ret := _m.Called(ctx, eventID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueScheduleTaskAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = rf(ctx, eventID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueScheduleTaskIn provides a mock function with given fields: ctx, eventID, delay
func (_m *TaskManager) EnqueueScheduleTaskIn(ctx context.Context, eventID int64, delay time.Duration) error {
	ret := _m.Called(ctx, eventID, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueScheduleTaskIn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Duration) error); ok {
		r0 = rf(ctx, eventID, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueTestTaskAt provides a mock function with given fields: ctx, username, _a2
func (_m *TaskManager) EnqueueTestTaskAt(ctx context.Context, username string, _a2 time.Time) error {
	ret := _m.Called(ctx, username, _a2)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueTestTaskAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, username, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskManager creates a new instance of TaskManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskManager {
	mock := &TaskManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
