// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TaskManager is an autogenerated mock type for the TaskManager type
type TaskManager struct {
	mock.Mock
}

// EnqueueTask provides a mock function with given fields: ctx, logID, taskType, queueType, delay
func (_m *TaskManager) EnqueueTask(ctx context.Context, logID int, taskType string, queueType string, delay time.Duration) error {
	ret := _m.Called(ctx, logID, taskType, queueType, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, time.Duration) error); ok {
		r0 = rf(ctx, logID, taskType, queueType, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueTaskAt provides a mock function with given fields: ctx, eventID, taskType, queueType, _a4
func (_m *TaskManager) EnqueueTaskAt(ctx context.Context, eventID int64, taskType string, queueType string, _a4 time.Time) error {
	ret := _m.Called(ctx, eventID, taskType, queueType, _a4)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueTaskAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Time) error); ok {
		r0 = rf(ctx, eventID, taskType, queueType, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueTaskIn provides a mock function with given fields: ctx, eventID, taskType, queueType, delay
func (_m *TaskManager) EnqueueTaskIn(ctx context.Context, eventID int64, taskType string, queueType string, delay time.Duration) error {
	ret := _m.Called(ctx, eventID, taskType, queueType, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueTaskIn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Duration) error); ok {
		r0 = rf(ctx, eventID, taskType, queueType, delay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskManager creates a new instance of TaskManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskManager {
	mock := &TaskManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
